"""create conversations and participants tables

Revision ID: 04ccfcfcb574
Revises: 0b919efa0469
Create Date: 2026-07-27 22:05:39.948052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ccfcfcb574'
down_revision: Union[str, Sequence[str], None] = '0b919efa0469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_conversation_user')
    )
    op.drop_index(op.f('idx_users_name_trgm'), table_name='users', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin', if_exists=True)
    op.drop_index(op.f('idx_users_username_trgm'), table_name='users', postgresql_ops={'username': 'gin_trgm_ops'}, postgresql_using='gin', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_username_trgm'), 'users', ['username'], unique=False, postgresql_ops={'username': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_users_name_trgm'), 'users', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_table('participants')
    op.drop_table('conversations')
    # ### end Alembic commands ###
