"""add last_read_at to participants

Revision ID: 6fa60a9ae1fa
Revises: cb99ce896ee7
Create Date: 2026-07-30 21:02:48.403834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa60a9ae1fa'
down_revision: Union[str, Sequence[str], None] = 'cb99ce896ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_messages_conversation_created_at'), table_name='messages')
    op.create_index('idx_messages_conversation_created_at', 'messages', ['conversation_id', 'created_at', 'id'], unique=False)
    op.add_column('participants', sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'last_read_at')
    op.drop_index('idx_messages_conversation_created_at', table_name='messages')
    op.create_index(op.f('idx_messages_conversation_created_at'), 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
